/**
 * IPC channel registry: the single source of truth for channel names.
 * Every channel is whitelisted here, registered in register.ts and
 * exposed through the preload bridge. The renderer can never call
 * anything that is not declared in this list.
 */
export const IPC = {
  PROJECT_LIST: 'project:list',
  PROJECT_CREATE: 'project:create',
  PROJECT_UPDATE: 'project:update',
  PROJECT_ARCHIVE: 'project:archive',
  FILE_LIST_BY_PROJECT: 'file:listByProject',
  FILE_ADD_REFERENCE: 'file:addReference',
  FILE_PICK_AND_ADD: 'file:pickAndAdd',
  FILE_REFRESH_PROJECT: 'file:refreshProject',
  FILE_REMOVE_FROM_PROJECT: 'file:removeFromProject',
  FILE_RELOCATE: 'file:relocate',
  FILE_UPDATE_TAGS: 'file:updateTags',
  FILE_MOVE_TO_PROJECT: 'file:moveToProjectFolder',
  FILE_THUMBNAIL: 'file:thumbnail',
  FILE_OPEN: 'file:open',
  FILE_OPEN_PATH: 'file:openPath',
  FILE_REVEAL: 'file:reveal',
  FILE_PICK_FILE: 'file:pickFile',
  FILE_PICK_FOLDER: 'file:pickFolder',
  LIBRARY_LIST: 'library:list',
  LIBRARY_COUNT: 'library:count',
  LIBRARY_TAGS: 'library:tags',
  LIBRARY_RECOMMEND: 'library:recommend',
  TASK_LIST_BY_PROJECT: 'task:listByProject',
  TASK_LIST_TODAY: 'task:listToday',
  TASK_CREATE: 'task:create',
  TASK_UPDATE: 'task:update',
  TASK_COMPLETE: 'task:complete',
  TASK_REOPEN: 'task:reopen',
  TASK_REMOVE: 'task:remove',
  TASK_ADD_FILE: 'task:addFile',
  TASK_REMOVE_FILE: 'task:removeFile',
  NOTE_LIST_BY_PROJECT: 'note:listByProject',
  NOTE_ADD: 'note:add',
  NOTE_CREATE: 'note:create',
  NOTE_GET: 'note:get',
  NOTE_SAVE: 'note:save',
  NOTE_REMOVE: 'note:remove',
  NOTE_BACKLINKS: 'note:backlinks',
  SEARCH_QUERY: 'search:query',
  SEARCH_SYNC: 'search:sync',
  EVENT_LIST_RANGE: 'event:listRange',
  EVENT_CREATE: 'event:create',
  EVENT_UPDATE: 'event:update',
  EVENT_REMOVE: 'event:remove',
  EVENT_EXPORT_ICS: 'event:exportIcs',
  EVENT_IMPORT_ICS: 'event:importIcs',
  AI_PARSE: 'ai:parse',
  AI_QUERY: 'ai:query',
  AI_SUMMARIZE: 'ai:summarize',
  AI_CHAT: 'ai:chat',
  AI_PREPARE: 'ai:prepare',
  AI_PREPARE_OPEN: 'ai:prepareOpen',
  AI_HABIT: 'ai:habit',
  AI_CONFIG_GET: 'ai:configGet',
  AI_CONFIG_SAVE: 'ai:configSave',
  AI_TEST: 'ai:test',
  HERMES_CHECK: 'hermes:check',
  HERMES_SEND: 'hermes:send',
  HERMES_STOP: 'hermes:stop',
  HERMES_RESPOND_PERMISSION: 'hermes:respondPermission',
  HERMES_OPEN_LOGIN: 'hermes:open-login',
  AGENT_LIST_PROVIDERS: 'agent:listProviders',
  AGENT_MODEL_LIST: 'agent:modelList',
  AGENT_SEND: 'agent:send',
  AGENT_STOP: 'agent:stop',
  AGENT_PROFILE_LIST: 'agent:profileList',
  AGENT_PROFILE_SAVE: 'agent:profileSave',
  AGENT_PROFILE_REMOVE: 'agent:profileRemove',
  SCENARIO_LIST: 'scenario:list',
  SCENARIO_CREATE: 'scenario:create',
  SCENARIO_UPDATE: 'scenario:update',
  SCENARIO_REMOVE: 'scenario:remove',
  SCENARIO_RENAME_AI: 'scenario:renameWithAi',
  SCENARIO_LEARN: 'scenario:learn',
  SCENARIO_CANDIDATES: 'scenario:candidates',
  SCENARIO_REVIEW_DAILY: 'scenario:reviewDaily',
  SCENARIO_ACCEPT_CANDIDATE: 'scenario:acceptCandidate',
  SCENARIO_DISMISS_CANDIDATE: 'scenario:dismissCandidate',
  SCENARIO_APPLY: 'scenario:apply',
  SCENARIO_APPLY_ITEMS: 'scenario:applyItems',
  SCENARIO_COMPLETE: 'scenario:complete',
  INBOX_LIST: 'inbox:list',
  INBOX_COUNT: 'inbox:count',
  INBOX_MARK_HANDLED: 'inbox:markHandled',
  INBOX_MARK_ALL: 'inbox:markAll',
  EMAIL_LIST: 'email:list',
  EMAIL_ACTIVE_ID: 'email:activeId',
  EMAIL_INFO: 'email:info',
  EMAIL_SAVE: 'email:save',
  EMAIL_SELECT: 'email:select',
  EMAIL_REMOVE: 'email:remove',
  EMAIL_CLEAR: 'email:clear',
  EMAIL_TEST: 'email:test',
  EMAIL_INBOX: 'email:inbox',
  EMAIL_GET: 'email:get',
  WATCHED_LIST: 'watched:list',
  WATCHED_ADD: 'watched:add',
  WATCHED_UPDATE: 'watched:update',
  WATCHED_REMOVE: 'watched:remove',
  WATCHED_SCAN: 'watched:scan',
  AUDIT_LIST: 'audit:list',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_ALL: 'settings:getAll',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_UNMAXIMIZE: 'window:unmaximize',
  WINDOW_IS_MAXIMIZED: 'window:isMaximized',
  WINDOW_CLOSE: 'window:close',
  APP_VERSION: 'app:version',
  UPDATE_CHECK: 'update:check',
  UPDATE_DOWNLOAD: 'update:download',
  UPDATE_INSTALL: 'update:install',
  UPDATE_STATUS: 'update:status',
  HOME_LAYOUT_GET: 'home:layoutGet',
  HOME_LAYOUT_SET: 'home:layoutSet',
  BOXES_LIST: 'boxes:list',
  BOXES_LAUNCH: 'boxes:launch',
  BOXES_ADD_PATHS: 'boxes:addPaths',
  BOXES_REMOVE: 'boxes:remove',
  BOXES_CREATE_FOLDER: 'boxes:createFolder',
  BOXES_PICK_ADD: 'boxes:pickAdd',
  BOXES_SHOW_IN_FOLDER: 'boxes:showInFolder',
  BOXES_TRASH: 'boxes:trash',
  CLIPBOARD_LIST: 'clipboard:list',
  CLIPBOARD_COPY: 'clipboard:copy',
  SYSTEM_STATS: 'system:stats',
  WEATHER_GET: 'weather:get',
  BACKUP_CREATE_MANUAL: 'backup:createManual',
  BACKUP_CREATE_AUTO: 'backup:createAuto'
} as const

/** Main → renderer push events. */
export const EVENTS = {
  FILE_CHANGED: 'file:changed',
  UPDATE_STATUS: 'update:status',
  CLIPBOARD_CHANGED: 'clipboard:changed',
  HERMES_EVENT: 'hermes:event'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
